#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

# http://lists.buildroot.org/pipermail/buildroot/2016-January/150846.html
# http://lists.busybox.net/pipermail/buildroot/2016-February/151270.html
#/var/spool is link to /tmp => crontabs are not persistent over boot
#mkdir -p /var/spool/cron/crontabs
#cp /root/crontab /var/spool/cron/crontabs/root
#Make cron work
ln -s /var/cron /var/spool/cron
start-stop-daemon -S -q -p /var/run/crond.pid --exec /usr/sbin/crond -- -l 8  

insmod /scripts/wiegand-driver.ko
#echo insmod /scripts/wiegand-gpio.ko
#insmod /scripts/match2_test/drv/test_drv.ko
#echo /scripts/match2_test/user/ wiegand
php -f /maasland_app/scripts/match_listener.php >> /var/log/match_listener.log &
#cat /sys/module/wiegand_gpio/sections/.text
#echo gdbserver --multi :10000

